spring:
  application:
    name: order
  datasource:
    url: jdbc:postgresql://192.168.56.38:5432/order
    username: postgres
    password: password123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082
logging:
  level:
    org:
      springframework:
        web: TRACE
    root: INFO
    com.ojasare.grpcservice: TRACE
  file:
    name: logs/order-service.log
