spring:
  application:
    name: api-gateway
server:
  port: 9000
logging:
  level:
    org:
      springframework:
        web: TRACE
    root: INFO
    com.ojasare.apigateway: TRACE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true