services:
  eureka-server:
    build:
      context: ./eureka-discovery-service/
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - grpc-network

  grpc-server:
    build:
      context: ./product/
      dockerfile: Dockerfile
    container_name: grpc-server
    ports:
      - "8081:8081"
      - "9090:9090"
    depends_on:
      - eureka-server
      - rabbitmq
    networks:
      - grpc-network

  grpc-client:
    build:
      context: ./order-service/
      dockerfile: Dockerfile
    container_name: grpc-client
    ports:
      - "8082:8082"
    depends_on:
      - grpc-server
      - eureka-server
      - rabbitmq
    networks:
      - grpc-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: testGuest
      RABBITMQ_DEFAULT_PASS: testGuest
    networks:
      - grpc-network

  api-gateway:
    build:
      context: ./api-gateway/
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "9000:9000"
    depends_on:
      - grpc-server
      - grpc-client
      - eureka-server
    networks:
      - grpc-network

networks:
  grpc-network:
    driver: bridge