spring:
  application:
    name: product
  datasource:
    url: jdbc:postgresql://postgres:5432/product
    username: postgres
    password: password123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
rabbitmq:
  queue:
    name: product_queue
server:
  port: 8081
logging:
  level:
    org:
      springframework:
        web: TRACE
    root: INFO
    com.ojasare.productservice: TRACE
grpc:
  server:
    port: 9090
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
